import { SnakeSkin } from '../types';

export const SNAKE_SKINS: SnakeSkin[] = [
  // 1. Classic Default
  {
    id: 'classic_nokia',
    name: 'Nokia 3310 Nguyên Bản',
    price: 0,
    rarity: 'classic',
    effect: 'none',
    headColor: '#2b5329',
    bodyColor: '#386633',
    tailColor: '#477c41',
    pattern: 'solid',
    soundVariant: 'classic',
    description: 'Thước đo của mọi huyền thoại. Rắn xanh pixel đậm chất Nokia bất tử.',
  },
  // 2. Emerald
  {
    id: 'emerald_pixel',
    name: 'Ngọc Lục Bảo',
    price: 150,
    rarity: 'classic',
    effect: 'none',
    headColor: '#10b981',
    bodyColor: '#34d399',
    tailColor: '#6ee7b7',
    pattern: 'dots',
    soundVariant: 'classic',
    description: 'Tinh thể ngọc lục bảo phát sáng nhẹ nhàng qua từng ô vuông.',
  },
  // 3. Cyber Ruby
  {
    id: 'cyber_ruby',
    name: 'Hồng Ngọc Arcade',
    price: 250,
    rarity: 'classic',
    effect: 'none',
    headColor: '#e11d48',
    bodyColor: '#f43f5e',
    tailColor: '#fb7185',
    pattern: 'stripes',
    soundVariant: 'arcade',
    description: 'Sắc đỏ rực rỡ của những chiếc máy thùng Arcade thập niên 90.',
  },
  // 4. Game Boy Gray
  {
    id: 'gameboy_mono',
    name: 'Game Boy Monochrome',
    price: 300,
    rarity: 'classic',
    effect: 'none',
    headColor: '#1f2937',
    bodyColor: '#374151',
    tailColor: '#4b5563',
    pattern: 'checker',
    soundVariant: 'classic',
    description: 'Bốn sắc độ xám hoài cổ trên chiếc máy chơi game huyền thoại.',
  },
  // 5. Desert Cobra
  {
    id: 'desert_cobra',
    name: 'Hổ Mang Sa Mạc',
    price: 400,
    rarity: 'rare',
    effect: 'none',
    headColor: '#d97706',
    bodyColor: '#f59e0b',
    tailColor: '#fbbf24',
    pattern: 'stripes',
    soundVariant: 'classic',
    description: 'Vàng óng cát cháy của loài mãng xà sa mạc Sahara.',
  },
  // 6. Glacier Viper
  {
    id: 'glacier_ice',
    name: 'Băng Xà Bắc Cực',
    price: 500,
    rarity: 'rare',
    effect: 'none',
    headColor: '#0284c7',
    bodyColor: '#38bdf8',
    tailColor: '#7dd3fc',
    pattern: 'dots',
    soundVariant: 'arcade',
    description: 'Hơi lạnh âm độ ngưng đọng trên từng mắt lưới chuyển động.',
  },
  // 7. Amethyst Python
  {
    id: 'amethyst_gem',
    name: 'Thạch Anh Tím',
    price: 600,
    rarity: 'rare',
    effect: 'none',
    headColor: '#7c3aed',
    bodyColor: '#a855f7',
    tailColor: '#c084fc',
    pattern: 'glow',
    soundVariant: 'ghost',
    description: 'Sức mạnh huyền bí từ quặng thạch anh hoàng gia.',
  },
  // 8. Toxic Slime
  {
    id: 'toxic_slime',
    name: 'Độc Dược Axit',
    price: 750,
    rarity: 'rare',
    effect: 'none',
    headColor: '#65a30d',
    bodyColor: '#84cc16',
    tailColor: '#a3e635',
    pattern: 'dots',
    soundVariant: 'arcade',
    description: 'Chất lỏng huỳnh quang phát sáng trong bóng đêm.',
  },
  // 9. Sunset Flamingo
  {
    id: 'sunset_flamingo',
    name: 'Hoàng Hôn Retro',
    price: 900,
    rarity: 'rare',
    effect: 'none',
    headColor: '#db2777',
    bodyColor: '#f472b6',
    tailColor: '#fbcfe8',
    pattern: 'stripes',
    soundVariant: 'classic',
    description: 'Tông màu Synthwave Miami lãng mạn của thập niên 80.',
  },
  // 10. Deep Ocean
  {
    id: 'deep_ocean',
    name: 'Thủy Quái Biển Sâu',
    price: 1100,
    rarity: 'rare',
    effect: 'none',
    headColor: '#0f766e',
    bodyColor: '#14b8a6',
    tailColor: '#2dd4bf',
    pattern: 'checker',
    soundVariant: 'classic',
    description: 'Dấu ấn của quái vật biển sâu thẳm ẩn mình dưới đáy vực.',
  },
  // 11. Brass Steampunk
  {
    id: 'steampunk_brass',
    name: 'Đồng Thau Cơ Khí',
    price: 1300,
    rarity: 'epic',
    effect: 'none',
    headColor: '#b45309',
    bodyColor: '#d97706',
    tailColor: '#fde68a',
    pattern: 'checker',
    soundVariant: 'classic',
    description: 'Khớp nối bánh răng bằng đồng đúc tỉ mỉ kiểu Steampunk.',
    hat: 'cap',
  },
  // 12. Rainbow 8-Bit
  {
    id: 'rainbow_chiptune',
    name: 'Cầu Vồng Chiptune',
    price: 1600,
    rarity: 'epic',
    effect: 'none',
    headColor: '#ec4899',
    bodyColor: '#eab308',
    tailColor: '#06b6d4',
    pattern: 'glow',
    soundVariant: 'arcade',
    description: 'Bản hòa ca đa sắc màu phát sáng theo nhịp đập 8-bit sống động.',
    hat: 'glasses',
  },
  // 13. Cyber Hacker
  {
    id: 'matrix_hacker',
    name: 'Mã Ma Trận Cyber',
    price: 1900,
    rarity: 'epic',
    effect: 'none',
    headColor: '#00ff66',
    bodyColor: '#00cc52',
    tailColor: '#008f39',
    pattern: 'stripes',
    soundVariant: 'arcade',
    description: 'Dòng mã xanh lục Matrix tuôn trào trên từng bước di chuyển.',
    hat: 'glasses',
  },
  // 14. Pure Gold Emperor
  {
    id: 'pure_gold',
    name: 'Hoàng Kim Đế Vương',
    price: 2400,
    rarity: 'epic',
    effect: 'none',
    headColor: '#ca8a04',
    bodyColor: '#eab308',
    tailColor: '#fef08a',
    pattern: 'glow',
    soundVariant: 'arcade',
    description: 'Đúc từ vàng 24K nguyên khối dành riêng cho những tay săn mồi cự phách.',
    hat: 'crown',
  },
  // 15. Dark Obsidian
  {
    id: 'dark_obsidian',
    name: 'Hắc Thạch Vô Ảnh',
    price: 2800,
    rarity: 'epic',
    effect: 'none',
    headColor: '#09090b',
    bodyColor: '#18181b',
    tailColor: '#27272a',
    pattern: 'checker',
    soundVariant: 'ghost',
    description: 'Đá núi lửa đen tuyền nuốt chửng mọi ánh sáng xung quanh.',
    hat: 'horns',
  },
  // 16. Candy Cane
  {
    id: 'candy_stripe',
    name: 'Kẹo Ngọt Giáng Sinh',
    price: 3200,
    rarity: 'epic',
    effect: 'none',
    headColor: '#dc2626',
    bodyColor: '#f87171',
    tailColor: '#ffffff',
    pattern: 'stripes',
    soundVariant: 'arcade',
    description: 'Sọc kẹo xoắn bắt mắt mang không khí lễ hội vui nhộn.',
  },
  // 17. Camo SpecOps
  {
    id: 'camo_military',
    name: 'Đặc Nhiệm Rừng Sâu',
    price: 3500,
    rarity: 'epic',
    effect: 'none',
    headColor: '#3f6212',
    bodyColor: '#4d7c0f',
    tailColor: '#65a30d',
    pattern: 'checker',
    soundVariant: 'classic',
    description: 'Ngụy trang quân đội tàng hình qua các bẫy địa hình phức tạp.',
    hat: 'cap',
  },

  // === 3 MYTHIC TOP-TIER SKINS WITH SPECIAL VISUAL EFFECTS ===
  // 18. MYTHIC 1: HỎA LONG (Tia Lửa & Khói Rực Lửa / Sparks & Embers)
  {
    id: 'mythic_fire_dragon',
    name: 'Hỏa Long Bất Diệt',
    price: 5000,
    rarity: 'mythic',
    effect: 'spark',
    headColor: '#ff2a00',
    bodyColor: '#ff7700',
    tailColor: '#ffcc00',
    pattern: 'glow',
    soundVariant: 'fire',
    description: '★ TỐI THƯỢNG: Phóng ra tia lửa than đỏ và hiệu ứng tàn tro bốc khói sau mỗi bước chuyển động.',
    hat: 'crown',
  },
  // 19. MYTHIC 2: U LINH (Hiệu Ứng Mờ Dần / Ethereal Fade Trail)
  {
    id: 'mythic_ghost_phantom',
    name: 'U Linh Bóng Đêm',
    price: 6500,
    rarity: 'mythic',
    effect: 'fade',
    headColor: '#38bdf8',
    bodyColor: '#818cf8',
    tailColor: '#c084fc',
    pattern: 'glow',
    soundVariant: 'ghost',
    description: '★ TỐI THƯỢNG: Thân thể mờ dần huyền bí tạo vệt bóng ma siêu thực lướt nhẹ như hư không.',
    hat: 'horns',
  },
  // 20. MYTHIC 3: LÔI THẦN (Tia Sét & Hồ Quang Điện / Electric Lightning Aura)
  {
    id: 'mythic_electric_thunder',
    name: 'Lôi Thần Bão Điện',
    price: 8000,
    rarity: 'mythic',
    effect: 'electric',
    headColor: '#facc15',
    bodyColor: '#38bdf8',
    tailColor: '#ffffff',
    pattern: 'glow',
    soundVariant: 'lightning',
    description: '★ TỐI THƯỢNG: Bao bọc bởi hồ quang sấm sét giật liên hồi và xung điện bùng nổ khi săn mồi.',
    hat: 'crown',
  },
];

export function getSkinById(id: string): SnakeSkin {
  const found = SNAKE_SKINS.find((s) => s.id === id);
  return found || SNAKE_SKINS[0];
}
